name: vnstat
title: vnStat
base: core22
adopt-info: vnstat
icon: snap/local/vnstat_icon.png
website: https://humdi.net/vnstat/
source-code: https://github.com/vergoh/vnstat
issues: https://github.com/vergoh/vnstat-snap/issues
license: GPL-2.0
summary: Console-based network traffic monitor
description: |
  vnStat is a console-based network traffic monitor that uses the network
  interface statistics provided by the kernel as information source. This
  means that vnStat won't actually be sniffing any traffic and also ensures
  light use of system resources regardless of network traffic rate.

  Once installed, this snap needs to be connected for full functionality:

     sudo snap connect vnstat:network-observe
     sudo snap restart vnstat

  For more information see https://github.com/vergoh/vnstat-snap

grade: stable
confinement: strict

architectures:
  - build-on: s390x
  - build-on: ppc64el
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64

apps:
  vnstat:
    command: usr/bin/vnstat --config $SNAP_DATA/options/config
    plugs: [network-observe]
  image: # results in vnstat.image
    command: usr/bin/vnstati --config $SNAP_DATA/options/config
  daemon: # results in vnstat.daemon
    command: usr/sbin/vnstatd --config $SNAP_DATA/options/config -n
    daemon: simple
    plugs: [network-observe]
    restart-delay: 10s
    restart-condition: on-failure
    stop-mode: sigterm
    stop-timeout: 10s

layout:
  /var/lib/vnstat:
    bind: $SNAP_DATA/var/lib/vnstat

parts:
  vnstat:
    plugin: autotools
    source: https://github.com/vergoh/vnstat
    source-type: git
    source-branch: master
    autotools-configure-parameters:
      - --prefix=/usr
      - --sysconfdir=/etc
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --abbrev=1 --tags --long)"
    build-packages:
      - pkg-config
      - libsqlite3-dev
      - libgd-dev
    stage-packages:
      - libsqlite3-0
      - libgd3
